spring:
  application:
    name: api-gateway
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true

# Swagger configuration for the Gateway
springdoc:
  swagger-ui:
    urls:
      - url: /products-service/v3/api-docs
        name: Products Service
      - url: /shopping-cart-service/v3/api-docs
        name: Shopping Cart Service
      - url: /sales-service/v3/api-docs
        name: Sales Service
  api-docs:
    enabled: true

server:
  port: 8000
