spring:
  application:
    name: shopping-cart-service

  datasource:
    url: jdbc:h2:mem:service_cart;MODE=MySQL;DB_CLOSE_DELAY=-1;
    driverClassName: org.h2.Driver
    username: sa
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    database-platform: org.hibernate.dialect.H2Dialect

  h2:
    console:
      enabled: true
      path: /h2-console

server:
  port: 8082

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka

resilience4j:
  circuitbreaker:
    instances:
      products-service:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10s
        failureRateThreshold: 50
        recordExceptions:
          - feign.RetryableException
          - feign.FeignException
          - feign.FeignException$ServiceUnavailable
          - feign.FeignException$InternalServerError
          - feign.FeignException$BadGateway
          - feign.FeignException$GatewayTimeout
          - java.net.ConnectException
          - java.io.IOException

  retry:
    instances:
      products-service:
        maxAttempts: 3
        waitDuration: 2s
        retryExceptions:
          - feign.RetryableException
          - feign.FeignException
          - feign.FeignException$ServiceUnavailable
          - feign.FeignException$InternalServerError
          - feign.FeignException$BadGateway
          - feign.FeignException$GatewayTimeout
          - java.net.ConnectException
